export {
  RegistryError,
  DeviceCodeStartSchema,
  TokenResponseSchema,
  BindResponseSchema,
  AspirationResponseSchema,
  EvalAddResponseSchema,
  EvalListResponseSchema,
  EvalSummarySchema,
  type DeviceCodeStart,
  type TokenResponse,
  type BindRequest,
  type BindResponse,
  type AspirationRequest,
  type AspirationResponse,
  type EvalAddRequest,
  type EvalAddResponse,
  type EvalListResponse,
  type EvalSummary,
} from './types.js';

export {
  startDeviceCode,
  pollForToken,
  bindAgent,
  addAspiration,
  addEval,
  listEvals,
  type RegistryDeps,
  type PollDeps,
} from './client.js';
